### ISSUE TITLE
Does not work if the repository is set to Private

### ISSUE THREAD

**Issue by BinaryHexer** [koumoul-dev/gh-pages-multi#1]
It seems if the repository is set to private on Github, this tool fails to correctly update the `gh-pages` branch or any other branch for that matter.

On executing the tool with the `--verbose` option, the relevant output is:
```
gh-pages-multi no modification to validate +112ms
```

It seems responsible code is:
```
    await exec(`git add -A`)
    const diffOut = await exec(`git diff --staged --name-only`)
    if (diffOut.length === 0) return console.log(`No modification to validate`)
```

If the same steps are executed manually using the terminal the output of `git diff --staged --name-only` is not empty.

So I really don't know what's going on here.

**Comment by BinaryHexer** [comment]
It seems just commenting out the line works:

```
// if (diffOut.length === 0) return console.log(`No modification to validate`)
```

**Comment by albanm** [comment]
Unfortunately I don't think removing this line entirely is acceptable.

Are you sure this problem is specific to private repos ? I would like to debug it, but I don't have private repos.

What is the output of the previous command "await exec(`git add -A`)" ?

**Comment by BinaryHexer** [comment]
Yeah, I did not mean that we should straight out remove that line.

Actually if you do remove that line and then try to publish without making any actual changes, then it will fail to commit.

I didn't get much time last week. I will try to find the root cause and report here.

**Comment by BinaryHexer** [comment]
Sorry I think this wasn't a issue with this repo. 

Someone in my team was using `yarn global add gh-pages-multi` instead of `yarn global add @koumoul/gh-pages-multi`.
